### ISSUE TITLE
Doesn't appear to work in NR 7.2.7

### ISSUE THREAD

**Issue by timdonovanuk** [ryzecdavid/node-red-show-value#3]
I've set path to:

- msg
- msg.payload
- msg.payload.percent (this is set by an earlier node).

All this node shows is:

![image](https://user-images.githubusercontent.com/8156439/103358224-f7f83000-4aac-11eb-86a6-3372217a4745.png)

With an error of `TypeError: Cannot read property 'payload' of undefined`. A debug node outputs the payload path fine.

**Comment by ryzecdavid** [comment]
The path is respective to message payload, so if you want to show percent property just set path to "percent".
